<?php

namespace App\Http\Requests\Widget;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class ClientUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(Request $request)
    {
        $client = $request->route('client');
        return [
            'first_name' => 'string|max:255',
            'last_name' => 'string|max:255',
            'father_name' => 'string|max:255',
            'sex' => 'in:male,female',
            'birthday' => 'date_format:Y-m-d',
            'email' => 'string|email|max:255|'.Rule::unique('clients')->ignore($client,'id'),
            'phone' =>'string|max:255|'.Rule::unique('clients')->ignore($client,'id'),
            'card_number' => 'numeric|digits_between:12,12',
            'card_number_optional' => 'numeric|digits_between:12,12',
            'comment'=>'string',
            /*'deposit'=>'numeric|between:0,99999999.99',
            'bonuses'=>'numeric|between:0,99999999.99',
            'invoice_sum'=>'numeric|between:0,99999999.99'*/
        ];
    }
    /**
     * @return array
     */
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function failedValidation(Validator $validator)
    {
        throw new HttpResponseException(response()->json(['ValidationError' => $validator->messages()],422));
    }
}
